<?php
return [
    'installed' => false,
    'app' => [
        'name' => 'SELO',
        'name_fa' => 'سلو',
        'url' => 'http://localhost',
        'timezone' => 'Asia/Tehran',
        'jwt_secret' => 'CHANGE_ME',
        'jwt_ttl_seconds' => 604800,
    ],
    'db' => [
        'host' => 'localhost',
        'name' => 'selo',
        'user' => 'root',
        'pass' => '',
        'prefix' => 'selo_',
    ],
    'uploads' => [
        'dir' => __DIR__ . '/../storage/uploads',
        'max_size' => 2 * 1024 * 1024,
        'media_dir' => __DIR__ . '/../storage/uploads/media',
        'media_max_size' => 20 * 1024 * 1024,
        'photo_max_size' => 5 * 1024 * 1024,
        'video_max_size' => 25 * 1024 * 1024,
        'voice_max_size' => 10 * 1024 * 1024,
        'file_max_size' => 20 * 1024 * 1024,
        'max_files_per_request' => 10,
        'max_photos_per_request' => 10,
        'max_videos_per_request' => 10,
        'thumbnail_max_size' => 480,
        'ffmpeg_path' => '',
        'ffprobe_path' => '',
    ],
    'realtime' => [
        'mode' => 'auto',
        'sse_retry_ms' => 2000,
        'sse_heartbeat_seconds' => 20,
        'sse_max_seconds' => 55,
        'sse_poll_active_ms' => 300,
        'sse_poll_min_ms' => 1000,
        'sse_poll_max_ms' => 5000,
        'sse_poll_jitter_ms' => 150,
        'sse_receipt_poll_ms' => 2000,
    ],
    'presence' => [
        'online_window_seconds' => 60,
        'ping_interval_seconds' => 15,
        'last_seen_touch_seconds' => 60,
    ],
    'reactions' => [
        'cooldown_seconds' => 2,
        'rate_limit' => [
            'max_attempts' => 12,
            'window_minutes' => 1,
            'lock_minutes' => 1,
        ],
    ],
    'calls' => [
        'enabled' => false,
        'signaling_url' => '',
        'signaling_secret' => 'CHANGE_ME',
        'token_ttl_seconds' => 604800,
        'ring_timeout_seconds' => 45,
        'rate_limit' => [
            'max_attempts' => 30,
            'window_minutes' => 1,
            'lock_minutes' => 1,
        ],
        'ice_servers' => [],
    ],
    'logging' => [
        'level' => 'INFO',
        'app_file' => __DIR__ . '/../storage/logs/app.log',
        'error_file' => __DIR__ . '/../storage/logs/error.log',
        'max_size_mb' => 10,
        'max_files' => 5,
    ],
];
