<?php
return [
    'installed' => false,
    'app' => [
        'name' => 'SELO',
        'name_fa' => 'سلو',
        'url' => 'http://localhost',
        'timezone' => 'Asia/Tehran',
        'jwt_secret' => 'CHANGE_ME',
        'jwt_ttl_seconds' => 604800,
        'enable_service_worker' => true,
    ],
    'db' => [
        'host' => 'localhost',
        'name' => 'selo',
        'user' => 'root',
        'pass' => '',
        'prefix' => 'selo_',
    ],
    'uploads' => [
        'dir' => __DIR__ . '/../storage/uploads',
        'max_size' => 2 * 1024 * 1024,
        'media_dir' => __DIR__ . '/../storage/uploads/media',
        'media_max_size' => 20 * 1024 * 1024,
        'user_total_quota_bytes' => 512 * 1024 * 1024,
        'user_daily_quota_bytes' => 128 * 1024 * 1024,
        'app_total_quota_bytes' => 2 * 1024 * 1024 * 1024,
        'app_total_files_limit' => 50000,
        'pending_ttl_seconds' => 6 * 60 * 60,
        'gc_max_items' => 25,
        'photo_max_size' => 5 * 1024 * 1024,
        'video_max_size' => 25 * 1024 * 1024,
        'voice_max_size' => 10 * 1024 * 1024,
        'file_max_size' => 20 * 1024 * 1024,
        'max_files_per_request' => 10,
        'max_photos_per_request' => 10,
        'max_videos_per_request' => 10,
        'thumbnail_max_size' => 480,
        'image_max_width' => 8000,
        'image_max_height' => 8000,
        'image_max_pixels' => 25000000,
        'ffmpeg_path' => '/usr/bin/ffmpeg',
        'ffprobe_path' => '/usr/bin/ffprobe',
        'shared_mode' => false,
        'disable_process_execution' => false,
        'media_process_timeout_seconds' => 4,
    ],
    'realtime' => [
        'mode' => 'poll',
        'sse_enabled' => false,
        'poll_per_user_concurrency' => 1,
        'poll_per_ip_concurrency' => 4,
        'sse_retry_ms' => 2000,
        'sse_heartbeat_seconds' => 20,
        'sse_max_seconds' => 55,
        'sse_poll_active_ms' => 300,
        'sse_poll_min_ms' => 1000,
        'sse_poll_max_ms' => 5000,
        'sse_poll_jitter_ms' => 150,
        'sse_receipt_poll_ms' => 2000,
        'stream_message_limit' => 60,
        'stream_receipt_limit' => 80,
        'stream_hydrate_max_messages' => 40,
    ],
    'presence' => [
        'online_window_seconds' => 60,
        'ping_interval_seconds' => 15,
        'last_seen_touch_seconds' => 60,
    ],
    'reactions' => [
        'cooldown_seconds' => 2,
        'rate_limit' => [
            'max_attempts' => 12,
            'window_minutes' => 1,
            'lock_minutes' => 1,
            'ttl_hours' => 6,
        ],
    ],
    'rate_limits' => [
        'max_body_bytes' => [
            'register' => 16 * 1024,
            'login' => 16 * 1024,
            'send' => 256 * 1024,
            'ack' => 128 * 1024,
            'upload' => 30 * 1024 * 1024,
        ],
        'max_array_items' => [
            'send_media_ids' => 20,
            'ack_message_ids' => 500,
        ],
        'endpoints' => [
            'ttl_hours' => 24,
            'default' => [
                'ip_burst' => 60,
                'user_burst' => 40,
                'window_seconds' => 60,
                'base_ban_seconds' => 15,
                'max_ban_seconds' => 900,
                'max_penalty_level' => 8,
            ],
            'register' => [
                'ip_burst' => 12,
                'user_burst' => 12,
                'window_seconds' => 60,
                'base_ban_seconds' => 60,
                'max_ban_seconds' => 3600,
                'max_penalty_level' => 10,
            ],
            'login' => [
                'ip_burst' => 30,
                'user_burst' => 30,
                'window_seconds' => 60,
                'base_ban_seconds' => 30,
                'max_ban_seconds' => 1800,
                'max_penalty_level' => 9,
            ],
            'upload' => [
                'ip_burst' => 15,
                'user_burst' => 10,
                'window_seconds' => 60,
                'base_ban_seconds' => 30,
                'max_ban_seconds' => 1800,
                'max_penalty_level' => 9,
            ],
            'send' => [
                'ip_burst' => 120,
                'user_burst' => 80,
                'window_seconds' => 60,
                'base_ban_seconds' => 10,
                'max_ban_seconds' => 600,
                'max_penalty_level' => 8,
            ],
            'ack' => [
                'ip_burst' => 200,
                'user_burst' => 160,
                'window_seconds' => 60,
                'base_ban_seconds' => 5,
                'max_ban_seconds' => 300,
                'max_penalty_level' => 7,
            ],
        ],
    ],
    'logging' => [
        'level' => 'INFO',
        'app_file' => __DIR__ . '/../storage/logs/app.log',
        'error_file' => __DIR__ . '/../storage/logs/error.log',
        'max_size_mb' => 10,
        'max_files' => 5,
    ],
    'filesystem' => [
        'dir_mode' => 0775,
        'file_mode' => 0664,
        'umask' => 0002,
    ],
];
